/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transcore;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URI;
import java.net.URL;

/**
 *
 * @author Jianying Chiang
 */
public class Login extends javax.swing.JFrame {
    Dimension dimension;
    int xMouse;
    int yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        dimension = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setLocation(dimension.width/2-getSize().width/2, dimension.height/2-getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        windowBar = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        windowTitle = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        logoPic = new javax.swing.JLabel();
        userPane = new javax.swing.JPanel();
        userBar = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        passPane = new javax.swing.JPanel();
        passBar = new javax.swing.JPanel();
        passField = new javax.swing.JTextField();
        loginButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        forgotPane = new javax.swing.JPanel();
        forgotLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 800));
        setMinimumSize(new java.awt.Dimension(600, 800));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(null);

        windowBar.setBackground(new java.awt.Color(0, 0, 0));
        windowBar.setPreferredSize(new java.awt.Dimension(600, 40));
        windowBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowBarMouseDragged(evt);
            }
        });
        windowBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowBarMousePressed(evt);
            }
        });

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.jpg"))); // NOI18N
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        windowTitle.setBackground(new java.awt.Color(255, 255, 255));
        windowTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        windowTitle.setForeground(new java.awt.Color(255, 255, 255));
        windowTitle.setText("TransCore Login");

        javax.swing.GroupLayout windowBarLayout = new javax.swing.GroupLayout(windowBar);
        windowBar.setLayout(windowBarLayout);
        windowBarLayout.setHorizontalGroup(
            windowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowBarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimizeButton)
                .addGap(18, 18, 18)
                .addComponent(windowTitle)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        windowBarLayout.setVerticalGroup(
            windowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowBarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(windowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(windowTitle)
                    .addGroup(windowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minimizeButton)
                        .addComponent(closeButton)))
                .addGap(8, 8, 8))
        );

        getContentPane().add(windowBar);
        windowBar.setBounds(0, 0, 600, 43);

        mainPane.setBackground(new java.awt.Color(255, 255, 255));
        mainPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPane.setPreferredSize(new java.awt.Dimension(600, 757));

        logoPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transCoreLogo.jpg"))); // NOI18N

        userPane.setBackground(new java.awt.Color(255, 255, 255));

        userBar.setBackground(new java.awt.Color(204, 204, 204));
        userBar.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout userBarLayout = new javax.swing.GroupLayout(userBar);
        userBar.setLayout(userBarLayout);
        userBarLayout.setHorizontalGroup(
            userBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        userBarLayout.setVerticalGroup(
            userBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        userField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        userField.setForeground(new java.awt.Color(153, 153, 153));
        userField.setText("Username");
        userField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userField.setPreferredSize(new java.awt.Dimension(96, 26));
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFieldMouseClicked(evt);
            }
        });
        userField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout userPaneLayout = new javax.swing.GroupLayout(userPane);
        userPane.setLayout(userPaneLayout);
        userPaneLayout.setHorizontalGroup(
            userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(userPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPaneLayout.setVerticalGroup(
            userPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPaneLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        passPane.setBackground(new java.awt.Color(255, 255, 255));
        passPane.setForeground(new java.awt.Color(153, 153, 153));
        passPane.setPreferredSize(new java.awt.Dimension(400, 100));

        passBar.setBackground(new java.awt.Color(204, 204, 204));
        passBar.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout passBarLayout = new javax.swing.GroupLayout(passBar);
        passBar.setLayout(passBarLayout);
        passBarLayout.setHorizontalGroup(
            passBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        passBarLayout.setVerticalGroup(
            passBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        passField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setText("Password");
        passField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passFieldMouseClicked(evt);
            }
        });
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout passPaneLayout = new javax.swing.GroupLayout(passPane);
        passPane.setLayout(passPaneLayout);
        passPaneLayout.setHorizontalGroup(
            passPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(passPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passPaneLayout.setVerticalGroup(
            passPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passPaneLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginButton.setBackground(new java.awt.Color(32, 89, 160));
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 89, 160), 5, true));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");

        javax.swing.GroupLayout loginButtonLayout = new javax.swing.GroupLayout(loginButton);
        loginButton.setLayout(loginButtonLayout);
        loginButtonLayout.setHorizontalGroup(
            loginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        loginButtonLayout.setVerticalGroup(
            loginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        forgotPane.setBackground(new java.awt.Color(255, 255, 255));
        forgotPane.setForeground(new java.awt.Color(153, 153, 153));

        forgotLabel.setBackground(new java.awt.Color(255, 255, 255));
        forgotLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        forgotLabel.setForeground(new java.awt.Color(153, 153, 153));
        forgotLabel.setText("Forgot the password?");
        forgotLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout forgotPaneLayout = new javax.swing.GroupLayout(forgotPane);
        forgotPane.setLayout(forgotPaneLayout);
        forgotPaneLayout.setHorizontalGroup(
            forgotPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(forgotLabel)
                .addGap(0, 0, 0))
        );
        forgotPaneLayout.setVerticalGroup(
            forgotPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(forgotLabel))
        );

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logoPic)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(forgotPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logoPic)
                .addGap(101, 101, 101)
                .addComponent(userPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(passPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(mainPane);
        mainPane.setBounds(0, 40, 600, 760);

        pack();
    }// </editor-fold>                        

    private void windowBarMouseDragged(java.awt.event.MouseEvent evt) {                                       
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - xMouse, y - yMouse);
    }                                      

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        System.exit(0);
    }                                        

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        setState(ICONIFIED);
    }                                           

    private void windowBarMousePressed(java.awt.event.MouseEvent evt) {                                       
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                      

    private void userFieldMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (userField.getText().equals("Username") && userEntry == false) {
            userEntry = true;
            userField.setForeground(new java.awt.Color(50, 50, 50));
            userField.setText("");
        }
    }                                      

    private void passFieldMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (passField.getText().equals("Password") && passEntry==false) {
            passEntry = true;
            passField.setForeground(new java.awt.Color(50, 50, 50));
            passField.setText("");
        }
    }                                      

    private void userFieldKeyTyped(java.awt.event.KeyEvent evt) {                                   
        if (userField.getText().equals("Username") && userEntry == false) {
            userEntry = true;
            userField.setForeground(new java.awt.Color(50, 50, 50));
            userField.setText("");
        }
    }                                  

    private void passFieldKeyTyped(java.awt.event.KeyEvent evt) {                                   
        if (passField.getText().equals("Password") && passEntry==false) {
            passEntry = true;
            passField.setForeground(new java.awt.Color(50, 50, 50));
            passField.setText("");
        }
    }                                  

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {                                         
        loginButton.setBackground(new java.awt.Color(82, 139, 210));
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(82, 139, 210), 5, true));
    }                                        

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {                                        
        loginButton.setBackground(new java.awt.Color(32, 89, 160));
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 89, 160), 5, true));
    }                                       

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        enteredUser = userField.getText();
        enteredPass = passField.getText();
        if (false) {
            
        }
        else {
            userBar.setBackground(new java.awt.Color(204,0,0));
            passBar.setBackground(new java.awt.Color(204,0,0));
        }
    }                                        

    private void forgotLabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        try {
            openWebpage(new URI("https://www.transcore.com/contact"));
        } catch(Exception e) {}
    }                                        
    
    public static boolean openWebpage(URI uri) {
    Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
    if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
        try {
            desktop.browse(uri);
            return true;
        } catch (Exception e) {}
    }
    return false;
}

    public static boolean openWebpage(URL url) {
        try {
            return openWebpage(url.toURI());
        } catch (Exception e) {}
        return false;
    }
    
    boolean userEntry = false;
    boolean passEntry = false;
    String enteredUser;
    String enteredPass;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JPanel forgotPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel loginButton;
    private javax.swing.JLabel logoPic;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPanel passBar;
    private javax.swing.JTextField passField;
    private javax.swing.JPanel passPane;
    private javax.swing.JPanel userBar;
    private javax.swing.JTextField userField;
    private javax.swing.JPanel userPane;
    private javax.swing.JPanel windowBar;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration                   
}
